type RacketEntry = {
  name: string;
  brand: string;
  category: string;
  head_size: string;
  weight: string;
  balance: string;
  stiffness: string;
  string_pattern: string;
  price_range: string;
  best_for_style: string[];
  best_for_priority: string[];
  best_for_level: string[];
  age_sweet_spot: string;
  gender_notes: string;
  first_racket_suitable: boolean;
  health_warning: string;
  strengths: string;
  weaknesses: string;
  ideal_profile: string;
  not_ideal_for: string;
  famous_users: string;
};

export const RACKET_DATABASE: RacketEntry[] = [
  {
    name: "Babolat Pure Aero",
    brand: "Babolat",
    category: "Spin & Power",
    head_size: "100 sq in",
    weight: "300g unstrung",
    balance: "320mm",
    stiffness: "71 RA",
    string_pattern: "16x19",
    price_range: "€200-260",
    best_for_style: ["aggressive baseliner", "defensive counter-puncher"],
    best_for_priority: ["spin", "power"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-50. May be too demanding for 50+ or juniors under 16 because of its stiffness.",
    gender_notes: "Unisex. Popular on both ATP and WTA tours.",
    first_racket_suitable: true,
    health_warning: "Players with elbow, wrist or shoulder concerns should look elsewhere.",
    strengths: "Good spin and power with decent control due to a tighter string pattern. Aerodynamic beam design for fast racket head speed. Forgiving on off-center hits. One of the most popular rackets on tour.",
    weaknesses: "Can feel stiff and muted to touch-oriented players. Not ideal for serve-and-volley or net play.",
    ideal_profile: "An intermediate-to-advanced aggressive baseliner aged 20-50 who wants to dominate rallies with heavy topspin. Also works for defensive counter-punchers.",
    not_ideal_for: "Beginners (too stiff), serve-and-volley players, players with arm issues, players over 50.",
    famous_users: "Rafael Nadal (retired), Alex Michelsen, Adrian Mannarino",
  },
  {
    name: "Babolat Pure Aero 98",
    brand: "Babolat",
    category: "Spin & Control",
    head_size: "98 sq in",
    weight: "305g unstrung",
    balance: "315mm",
    stiffness: "70 RA",
    string_pattern: "16x20",
    price_range: "€210-260",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["spin", "control"],
    best_for_level: ["advanced"],
    age_sweet_spot: "25-35. Demanding frame that requires good fitness and technique.",
    gender_notes: "More popular among male players due to its weight distribution.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. Not arm-friendly. Players with elbow, wrist or shoulder concerns should look elsewhere.",
    strengths: "Best of both worlds — Pure Aero's spin in a more controlled package. Smaller head and thinner beam give better feel and placement.",
    weaknesses: "Smaller sweet spot. Less power — you need to generate your own. Heavier swing weight demands fitness.",
    ideal_profile: "An advanced all-court player or aggressive baseliner who wants the Pure Aero's spin but with more control and precision.",
    not_ideal_for: "Beginners, intermediates, players wanting easy power, anyone with arm issues.",
    famous_users: "Carlos Alcaraz, Felix Auger-Aliassime, Holger Rune",
  },
  {
    name: "Babolat Pure Aero Lite",
    brand: "Babolat",
    category: "Spin & Power (Lightweight)",
    head_size: "100 sq in",
    weight: "270g unstrung",
    balance: "330mm (head-heavy)",
    stiffness: "71 RA",
    string_pattern: "16x19",
    price_range: "€180-230",
    best_for_style: ["aggressive baseliner", "defensive counter-puncher"],
    best_for_priority: ["spin", "power"],
    best_for_level: ["beginner", "intermediate"],
    age_sweet_spot: "All ages. Light enough for juniors 14+, seniors 50+, anyone who finds 300g too heavy.",
    gender_notes: "Very popular among female players and older male players.",
    first_racket_suitable: true,
    health_warning: "Same stiffness as the full Pure Aero (71 RA). Players with arm issues should still consider softer frames.",
    strengths: "All the spin benefits of the Pure Aero in a lighter, more maneuverable package. Head-heavy balance compensates for lower weight.",
    weaknesses: "Less stable than the full-weight version against heavy hitters.",
    ideal_profile: "A beginner or intermediate player of any age who wants the Pure Aero's spin DNA but needs a lighter frame. Perfect for women, juniors 14-18, men over 45.",
    not_ideal_for: "Advanced players (not enough stability), powerful hitters.",
    famous_users: "Popular among WTA players and club competitors",
  },
  {
    name: "Babolat Pure Aero Team",
    brand: "Babolat",
    category: "Spin & Power (Lightweight)",
    head_size: "100 sq in",
    weight: "285g unstrung",
    balance: "320mm",
    stiffness: "70 RA",
    string_pattern: "16x19",
    price_range: "€180-230",
    best_for_style: ["aggressive baseliner", "defensive counter-puncher"],
    best_for_priority: ["spin", "power"],
    best_for_level: ["beginner", "intermediate"],
    age_sweet_spot: "All ages. Light enough for juniors 14+, seniors 50+.",
    gender_notes: "Very popular among female players and older male players.",
    first_racket_suitable: true,
    health_warning: "Same stiffness as the full Pure Aero (71 RA). Players with arm issues should consider softer frames.",
    strengths: "All the spin benefits of the Pure Aero in a lighter, more maneuverable package.",
    weaknesses: "Less stable than the full-weight version against heavy hitters.",
    ideal_profile: "A beginner or intermediate player who wants the Pure Aero's spin DNA but needs a lighter frame.",
    not_ideal_for: "Advanced players, powerful hitters.",
    famous_users: "Popular among WTA players and club competitors",
  },
  {
    name: "Babolat Pure Drive",
    brand: "Babolat",
    category: "Power",
    head_size: "100 sq in",
    weight: "300g unstrung",
    balance: "320mm",
    stiffness: "72 RA",
    string_pattern: "16x19",
    price_range: "€200-250",
    best_for_style: ["aggressive baseliner", "defensive counter-puncher"],
    best_for_priority: ["power"],
    best_for_level: ["beginner", "intermediate", "advanced"],
    age_sweet_spot: "All ages. A versatile frame that suits a wide range of players.",
    gender_notes: "Unisex. Extremely popular at club and professional level.",
    first_racket_suitable: true,
    health_warning: "One of the stiffest frames on the market (72 RA). Can lead to wrist pain, tennis elbow or shoulder pain for sensitive players.",
    strengths: "Controlled power. Maximum ball speed with less effort. Excellent for aggressive returns and deep baseline rallies. Excellent serving frame.",
    weaknesses: "The stiffest Babolat frame. Can lack feel with wrong string setup.",
    ideal_profile: "A versatile frame that suits a wide range of players regardless of age, gender, or skill level who want power.",
    not_ideal_for: "Anyone with arm issues, finesse players, serve-and-volley players.",
    famous_users: "Previously used by many ATP/WTA players at various career stages",
  },
  {
    name: "Babolat Pure Strike 98 16x19",
    brand: "Babolat",
    category: "Control & Precision",
    head_size: "98 sq in",
    weight: "305g unstrung",
    balance: "320mm",
    stiffness: "67 RA",
    string_pattern: "16x19",
    price_range: "€210-260",
    best_for_style: ["aggressive baseliner", "all-court"],
    best_for_priority: ["control", "spin", "power"],
    best_for_level: ["advanced"],
    age_sweet_spot: "20-40. Suits fit players with developed technique.",
    gender_notes: "Unisex. Used on both tours.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness (67 RA). Reasonable for most players but those with chronic arm issues should consider softer frames.",
    strengths: "Precision instrument of Babolat's lineup. Clean feel with excellent feedback. Great blend of control and spin.",
    weaknesses: "Less raw power than Pure Drive or Pure Aero. Demands good technique. Smaller sweet spot.",
    ideal_profile: "An advanced aggressive baseliner or all-court player who values control and precision. The thinking player's Babolat.",
    not_ideal_for: "Beginners, pure power seekers, players who need maximum forgiveness.",
    famous_users: "Dominic Thiem (previously)",
  },
  {
    name: "Babolat Pure Strike 100 16x20",
    brand: "Babolat",
    category: "Control & Comfort",
    head_size: "100 sq in",
    weight: "300g unstrung",
    balance: "320mm",
    stiffness: "67 RA",
    string_pattern: "16x20",
    price_range: "€200-250",
    best_for_style: ["aggressive baseliner", "all-court"],
    best_for_priority: ["comfort", "control"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "20-45. More forgiving than the 98, suitable for a wider range.",
    gender_notes: "Unisex. Good transition racket from intermediate to advanced.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. More comfortable than the Pure Drive or Pure Aero.",
    strengths: "Comfortable Pure Strike. Larger head gives more forgiveness. Dense 16x20 pattern adds control and a plusher feel. Great middle ground between power and control.",
    weaknesses: "Less spin than 16x19 patterns. Not as precise as the 98 version.",
    ideal_profile: "An intermediate-to-advanced player who wants control and comfort without the demanding nature of the 98.",
    not_ideal_for: "Pure spin players, beginners.",
    famous_users: "",
  },
  {
    name: "Babolat Pure Strike 18x20",
    brand: "Babolat",
    category: "Precision & Control",
    head_size: "98 sq in",
    weight: "305g unstrung",
    balance: "320mm",
    stiffness: "67 RA",
    string_pattern: "18x20",
    price_range: "€210-260",
    best_for_style: ["serve and volley", "all-court"],
    best_for_priority: ["control"],
    best_for_level: ["advanced"],
    age_sweet_spot: "20-40. Demanding frame for technically complete players.",
    gender_notes: "More popular among male players with strong technique.",
    first_racket_suitable: false,
    health_warning: "Dense string pattern and weight demand good technique.",
    strengths: "Maximum control. The dense 18x20 pattern gives surgical precision on flat shots, slices, and volleys. The serve-and-volley player's Babolat.",
    weaknesses: "Least spin-friendly Babolat. Demands you generate all your own power.",
    ideal_profile: "An advanced serve-and-volley or all-court player who prioritises placement over power.",
    not_ideal_for: "Spin-dependent players, beginners, intermediates, power seekers.",
    famous_users: "",
  },
  {
    name: "Head Speed MP",
    brand: "Head",
    category: "All-Court Performance",
    head_size: "100 sq in",
    weight: "300g unstrung",
    balance: "320mm",
    stiffness: "64 RA",
    string_pattern: "16x19",
    price_range: "€220-270",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["control", "power", "spin"],
    best_for_level: ["advanced"],
    age_sweet_spot: "20-40. Suits fit, technically proficient players.",
    gender_notes: "Unisex. Djokovic's racket of choice.",
    first_racket_suitable: false,
    health_warning: "Lower stiffness (64 RA) makes it more arm-friendly than most performance frames.",
    strengths: "The most versatile racket in Head's lineup. Does everything well — baseline, net, serve. Lower stiffness than competitors means better comfort.",
    weaknesses: "Doesn't excel in any single area the way specialised frames do.",
    ideal_profile: "An advanced all-court player who wants one racket that does everything well. The Swiss Army knife of tennis rackets.",
    not_ideal_for: "Beginners, pure spin seekers, pure power seekers.",
    famous_users: "Novak Djokovic, Alexander Zverev",
  },
  {
    name: "Head Extreme MP",
    brand: "Head",
    category: "Spin & Power",
    head_size: "100 sq in",
    weight: "300g unstrung",
    balance: "320mm",
    stiffness: "68 RA",
    string_pattern: "16x19",
    price_range: "€210-260",
    best_for_style: ["aggressive baseliner"],
    best_for_priority: ["spin", "power"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "18-40.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. More comfortable than the Pure Aero.",
    strengths: "Head's spin machine. Slightly more comfortable than the Pure Aero while delivering similar spin.",
    weaknesses: "Less raw spin than the Pure Aero. Can feel underpowered for players who don't generate pace.",
    ideal_profile: "An intermediate-to-advanced aggressive baseliner who wants spin and power with better comfort than the Pure Aero.",
    not_ideal_for: "Serve-and-volley, beginners, players wanting maximum control.",
    famous_users: "Jannik Sinner (previously), Matteo Berrettini",
  },
  {
    name: "Head Gravity MP",
    brand: "Head",
    category: "Comfort & Versatility",
    head_size: "100 sq in",
    weight: "295g unstrung",
    balance: "325mm",
    stiffness: "63 RA",
    string_pattern: "16x20",
    price_range: "€210-260",
    best_for_style: ["all-court", "defensive counter-puncher"],
    best_for_priority: ["comfort", "control"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "All ages 18+. Comfortable and not too heavy.",
    gender_notes: "Unisex. Particularly popular among female advanced players.",
    first_racket_suitable: false,
    health_warning: "Low stiffness (63 RA). One of the more arm-friendly performance frames.",
    strengths: "Very comfortable. Good for players who use variety — slices, drop shots, flat drives, lobs. The tactician's racket.",
    weaknesses: "Doesn't excel in power or spin. Dense 16x20 pattern limits topspin generation.",
    ideal_profile: "An intermediate-to-advanced all-court player who values comfort and shot variety. Great for players who outthink opponents.",
    not_ideal_for: "Pure spin players, power seekers, beginners.",
    famous_users: "Alexander Zverev (previously)",
  },
  {
    name: "Head Radical MP",
    brand: "Head",
    category: "All-Court Control",
    head_size: "98 sq in",
    weight: "300g unstrung",
    balance: "320mm",
    stiffness: "63 RA",
    string_pattern: "16x19",
    price_range: "€200-250",
    best_for_style: ["all-court", "serve and volley"],
    best_for_priority: ["control", "comfort"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "20-45.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Low stiffness (63 RA). Arm-friendly for a performance frame.",
    strengths: "Balanced all-rounder. Good control without being overly demanding. Comfortable feel with adequate power.",
    weaknesses: "Not as spin-friendly as the Extreme. Not as powerful as stiffer frames.",
    ideal_profile: "An all-court player or serve-and-volley player who wants a comfortable, controlled frame.",
    not_ideal_for: "Spin-heavy players, beginners, pure power seekers.",
    famous_users: "Andy Murray (previously)",
  },
  {
    name: "Head Prestige MP",
    brand: "Head",
    category: "Pure Control",
    head_size: "98 sq in",
    weight: "320g unstrung",
    balance: "310mm (head-light)",
    stiffness: "59 RA",
    string_pattern: "18x20",
    price_range: "€220-270",
    best_for_style: ["serve and volley", "all-court"],
    best_for_priority: ["control"],
    best_for_level: ["advanced"],
    age_sweet_spot: "20-40. Extremely demanding. Requires strength and fitness.",
    gender_notes: "Predominantly used by strong male players.",
    first_racket_suitable: false,
    health_warning: "Very low stiffness (59 RA) — excellent arm comfort despite heavy weight. Best for players with arm issues WHO have the strength to swing it.",
    strengths: "The ultimate control racket. Pinpoint precision. Very low stiffness means superb feel and touch.",
    weaknesses: "Extremely heavy swing weight. Zero free power. You generate everything yourself. Not forgiving on mis-hits.",
    ideal_profile: "An advanced serve-and-volley or all-court player who demands maximum control and has the fitness to handle a heavy frame.",
    not_ideal_for: "Everyone except advanced/pro players with excellent technique.",
    famous_users: "Marin Cilic (previously), Gael Monfils (previously)",
  },
  {
    name: "Head Boom MP",
    brand: "Head",
    category: "Power & Comfort (Entry-Level Performance)",
    head_size: "100 sq in",
    weight: "295g unstrung",
    balance: "320mm",
    stiffness: "63 RA",
    string_pattern: "16x19",
    price_range: "€190-240",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["power", "comfort"],
    best_for_level: ["beginner", "intermediate"],
    age_sweet_spot: "All ages. Accessible weight and comfortable feel.",
    gender_notes: "Unisex. Good option for female players wanting a performance frame.",
    first_racket_suitable: true,
    health_warning: "Low stiffness (63 RA). Arm-friendly. Good choice for players with elbow or wrist concerns.",
    strengths: "Comfortable, forgiving, and powerful enough for developing players. A genuine performance racket that doesn't punish beginners.",
    weaknesses: "Not enough control for advanced players. You'll outgrow it as your technique improves.",
    ideal_profile: "A beginner or intermediate player of any age who wants a comfortable, forgiving racket that still plays like a real performance frame.",
    not_ideal_for: "Advanced players, pure power seekers at advanced level.",
    famous_users: "Popular at club level",
  },
  {
    name: "Wilson Blade 98 v9",
    brand: "Wilson",
    category: "Control & Feel",
    head_size: "98 sq in",
    weight: "305g unstrung",
    balance: "320mm",
    stiffness: "62 RA",
    string_pattern: "16x19",
    price_range: "€230-270",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["control", "comfort"],
    best_for_level: ["advanced"],
    age_sweet_spot: "20-40. Demanding but rewarding for fit, technical players.",
    gender_notes: "Unisex. Previously Serena Williams' weapon.",
    first_racket_suitable: false,
    health_warning: "Low stiffness (62 RA). Very arm-friendly for a performance frame.",
    strengths: "Exceptional feel and feedback. Low stiffness absorbs shock beautifully. Great for precise shot-making and variety.",
    weaknesses: "Requires good technique to generate power. Not forgiving on mis-hits.",
    ideal_profile: "An advanced all-court player who values feel, precision, and control over raw power.",
    not_ideal_for: "Beginners, intermediates, power seekers.",
    famous_users: "Previously Serena Williams, Milos Raonic",
  },
  {
    name: "Wilson Clash 100",
    brand: "Wilson",
    category: "Comfort & Power",
    head_size: "100 sq in",
    weight: "295g unstrung",
    balance: "312mm",
    stiffness: "55 RA",
    string_pattern: "16x19",
    price_range: "€210-250",
    best_for_style: ["all-court", "defensive counter-puncher"],
    best_for_priority: ["comfort"],
    best_for_level: ["beginner", "intermediate", "advanced"],
    age_sweet_spot: "All ages. The most comfortable performance racket. Especially good for 40+.",
    gender_notes: "Unisex. Very popular among female players and seniors.",
    first_racket_suitable: true,
    health_warning: "THE arm-friendly racket. At 55 RA, it's the softest performance frame available. #1 recommendation for players with tennis elbow, wrist pain, or shoulder issues.",
    strengths: "Unmatched comfort. FreeFlex technology bends to absorb shock while delivering power. You can play for hours without arm fatigue.",
    weaknesses: "Can feel mushy to players used to crisp frames. Lacks surgical precision of stiffer control frames.",
    ideal_profile: "ANY player who prioritises comfort — due to arm injuries, age, or preference. Especially for players returning from tennis elbow, seniors, and anyone playing 3+ times per week.",
    not_ideal_for: "Players who want maximum control and precision, players who like crisp stiff feel.",
    famous_users: "Popular among club players, seniors, and players recovering from injury",
  },
  {
    name: "Wilson Pro Staff 97 v14",
    brand: "Wilson",
    category: "Classic Control",
    head_size: "97 sq in",
    weight: "315g unstrung",
    balance: "310mm (head-light)",
    stiffness: "64 RA",
    string_pattern: "16x19",
    price_range: "€240-280",
    best_for_style: ["serve and volley", "all-court"],
    best_for_priority: ["control"],
    best_for_level: ["advanced"],
    age_sweet_spot: "20-40. Heavy and demanding. Requires excellent fitness.",
    gender_notes: "Predominantly used by strong male players.",
    first_racket_suitable: false,
    health_warning: "Heavy but not overly stiff. Weight can stress shoulders on serves.",
    strengths: "Federer's legacy frame. Head-light balance makes it surprisingly maneuverable at the net. Beautiful feel on volleys and touch shots.",
    weaknesses: "Very heavy. Demands excellent technique and timing. Less spin-friendly than modern open-pattern rackets.",
    ideal_profile: "An advanced serve-and-volley or classic all-court player who appreciates precision, feel, and racket heritage.",
    not_ideal_for: "Everyone except strong advanced players.",
    famous_users: "Roger Federer (retired), Stefanos Tsitsipas",
  },
  {
    name: "Wilson Burn 100LS",
    brand: "Wilson",
    category: "Beginner Power",
    head_size: "100 sq in",
    weight: "280g unstrung",
    balance: "330mm (head-heavy)",
    stiffness: "69 RA",
    string_pattern: "18x16",
    price_range: "€120-160",
    best_for_style: ["all-court"],
    best_for_priority: ["power", "spin"],
    best_for_level: ["beginner"],
    age_sweet_spot: "All ages. Light and easy to swing.",
    gender_notes: "Unisex. Popular among female beginners.",
    first_racket_suitable: true,
    health_warning: "Moderate stiffness but light weight reduces impact shock. Generally fine for most players.",
    strengths: "Light, affordable, and easy to swing. Spin-friendly reverse string pattern. Gets beginners playing real tennis quickly.",
    weaknesses: "Very basic construction. Not stable against heavy hitters. You'll outgrow it within 1-2 years.",
    ideal_profile: "A total beginner who needs an affordable, light racket to start learning.",
    not_ideal_for: "Anyone beyond beginner level. Not a long-term racket.",
    famous_users: "Designed for recreational beginners",
  },
  {
    name: "Yonex EZONE 100",
    brand: "Yonex",
    category: "Power & Comfort",
    head_size: "100 sq in",
    weight: "300g unstrung",
    balance: "320mm",
    stiffness: "68 RA",
    string_pattern: "16x19",
    price_range: "€220-260",
    best_for_style: ["aggressive baseliner", "all-court"],
    best_for_priority: ["power", "comfort"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "18-45. Comfortable enough for older players, powerful enough for younger ones.",
    gender_notes: "Unisex. Very popular on WTA tour.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness but Yonex's isometric head shape distributes impact well. More arm-friendly than the Pure Aero or Pure Drive despite similar stiffness numbers.",
    strengths: "Best blend of power and comfort in a 300g frame. Isometric head shape gives largest sweet spot in its class. Comfortable on off-center hits.",
    weaknesses: "Not as spin-focused as the Pure Aero. Not as precise as 98 sq in control frames.",
    ideal_profile: "An intermediate-to-advanced player who wants power AND comfort. Great for players switching from stiff frames due to arm concerns.",
    not_ideal_for: "Pure spin seekers, maximum control seekers.",
    famous_users: "Naomi Osaka, Nick Kyrgios",
  },
  {
    name: "Yonex VCORE 98",
    brand: "Yonex",
    category: "Spin & Control",
    head_size: "98 sq in",
    weight: "305g unstrung",
    balance: "320mm",
    stiffness: "65 RA",
    string_pattern: "16x19",
    price_range: "€220-260",
    best_for_style: ["aggressive baseliner"],
    best_for_priority: ["spin", "control"],
    best_for_level: ["advanced"],
    age_sweet_spot: "18-35. Demanding but rewards good technique with massive spin.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. Comfortable for a performance frame. Better than the Pure Aero for arm health.",
    strengths: "Exceptional spin generation for a 98 sq in control frame. Control-frame precision with spin-frame topspin. Comfortable feel.",
    weaknesses: "Smaller sweet spot. Less raw power. Demands clean technique.",
    ideal_profile: "An advanced aggressive baseliner who wants maximum spin from a control-oriented frame.",
    not_ideal_for: "Beginners, intermediates, comfort seekers, serve-and-volley.",
    famous_users: "Casper Ruud",
  },
  {
    name: "Tecnifibre Tempo 298",
    brand: "Tecnifibre",
    category: "All-Court Control & Feel",
    head_size: "98 sq in",
    weight: "298g unstrung",
    balance: "320mm",
    stiffness: "63 RA",
    string_pattern: "16x19",
    price_range: "€190-240",
    best_for_style: ["all-court"],
    best_for_priority: ["control", "comfort"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "20-45.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Low stiffness (63 RA). Arm-friendly. Good for players with mild arm concerns.",
    strengths: "Excellent comfort and feel. Great touch at the net. Underrated brand that often outperforms more expensive options. Good value for money.",
    weaknesses: "Less brand recognition. Not as widely available for demo/testing.",
    ideal_profile: "An intermediate-to-advanced all-court player who values feel and comfort. The hidden gem for players willing to look beyond the big brands.",
    not_ideal_for: "Brand-conscious players, beginners, pure power seekers.",
    famous_users: "Daniil Medvedev",
  },
  {
    name: "Dunlop CX 200",
    brand: "Dunlop",
    category: "Control & Precision",
    head_size: "98 sq in",
    weight: "305g unstrung",
    balance: "320mm",
    stiffness: "65 RA",
    string_pattern: "16x19",
    price_range: "€190-240",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["control"],
    best_for_level: ["advanced"],
    age_sweet_spot: "20-40.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. Reasonable for arm health.",
    strengths: "Excellent control frame with good feel. Sonic Core technology improves vibration dampening. Great value.",
    weaknesses: "Less power than competitors. Less brand cachet.",
    ideal_profile: "An advanced all-court player who wants a quality control frame without paying Wilson or Head premium prices.",
    not_ideal_for: "Beginners, power seekers, brand-conscious players.",
    famous_users: "Kevin Anderson (retired)",
  },
  {
    name: "Dunlop SX 300",
    brand: "Dunlop",
    category: "Spin & Power",
    head_size: "100 sq in",
    weight: "300g unstrung",
    balance: "320mm",
    stiffness: "67 RA",
    string_pattern: "16x19",
    price_range: "€180-230",
    best_for_style: ["aggressive baseliner"],
    best_for_priority: ["spin", "power"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "18-40.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. Average arm-friendliness.",
    strengths: "Good topspin generation with a comfortable feel. Spin Boost grommets amplify string movement. Competitive alternative to the Pure Aero at a lower price.",
    weaknesses: "Less brand recognition. Not quite the spin level of the Pure Aero.",
    ideal_profile: "An intermediate-to-advanced aggressive baseliner wanting a spin-focused racket at a better price than Babolat or Head alternatives.",
    not_ideal_for: "Beginners, control purists, brand-conscious players.",
    famous_users: "",
  },
  {
    name: "Diadem Elevate 98",
    brand: "Diadem",
    category: "Control & Power",
    head_size: "98 sq in",
    weight: "305g unstrung",
    balance: "320mm",
    stiffness: "64 RA",
    string_pattern: "16x19",
    price_range: "€180-220",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["control", "power"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "20-40.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Low stiffness. Arm-friendly.",
    strengths: "Clean, modern design with excellent feel. High-quality Japanese carbon. Outstanding value — premium performance at a mid-range price.",
    weaknesses: "Very new brand — limited track record. Harder to find for demo.",
    ideal_profile: "An intermediate-to-advanced player who doesn't care about brand name and wants a high-quality, well-priced racket.",
    not_ideal_for: "Brand-conscious players, beginners, players who want to try before buying.",
    famous_users: "Growing presence among college and lower-tour professionals",
  },
  {
    name: "Diadem Nova 100",
    brand: "Diadem",
    category: "Power & Spin",
    head_size: "100 sq in",
    weight: "300g unstrung",
    balance: "320mm",
    stiffness: "67 RA",
    string_pattern: "16x19",
    price_range: "€170-210",
    best_for_style: ["aggressive baseliner", "all-court"],
    best_for_priority: ["power", "spin"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "18-40.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. Average arm-friendliness.",
    strengths: "Power-oriented frame with good spin. Excellent price-to-performance ratio. Japanese carbon construction.",
    weaknesses: "New brand with limited recognition. Harder to find for testing.",
    ideal_profile: "An intermediate-to-advanced aggressive baseliner looking for a powerful, spin-friendly frame at a price well below the big brands.",
    not_ideal_for: "Brand loyalists, beginners, players who need to demo extensively.",
    famous_users: "Emerging presence in college tennis",
  },
  {
    name: "Babolat Boost Aero",
    brand: "Babolat",
    category: "Beginner",
    head_size: "102 sq in",
    weight: "260g unstrung",
    balance: "340mm (head-heavy)",
    stiffness: "71 RA",
    string_pattern: "16x19",
    price_range: "€80-110",
    best_for_style: ["all-court"],
    best_for_priority: ["power", "comfort"],
    best_for_level: ["beginner"],
    age_sweet_spot: "All ages. Designed for absolute beginners.",
    gender_notes: "Unisex.",
    first_racket_suitable: true,
    health_warning: "Stiff but very light, reducing impact shock. Fine for beginners.",
    strengths: "Pre-strung and ready to play. Very light and easy to swing. Most affordable entry point to tennis.",
    weaknesses: "Very basic construction. You'll outgrow it quickly. Limited feel.",
    ideal_profile: "A complete beginner on a budget who wants to try tennis without a big investment.",
    not_ideal_for: "Anyone who plays more than once a week.",
    famous_users: "Entry-level recreational players",
  },
  {
    name: "Head MX Attitude Elite",
    brand: "Head",
    category: "Beginner",
    head_size: "105 sq in",
    weight: "270g unstrung",
    balance: "335mm (head-heavy)",
    stiffness: "68 RA",
    string_pattern: "16x19",
    price_range: "€50-80",
    best_for_style: ["all-court"],
    best_for_priority: ["power", "comfort"],
    best_for_level: ["beginner"],
    age_sweet_spot: "All ages.",
    gender_notes: "Unisex. Popular among female beginners.",
    first_racket_suitable: true,
    health_warning: "Light weight is easy on joints.",
    strengths: "The cheapest way to start playing tennis. Oversized head is very forgiving. Available everywhere.",
    weaknesses: "Almost no feel or feedback. You'll outgrow it in weeks if you take lessons.",
    ideal_profile: "Someone who wants to try tennis for the first time with minimal investment.",
    not_ideal_for: "Anyone who plans to play regularly.",
    famous_users: "",
  },
];

export function getRacketDatabaseText(): string {
  return RACKET_DATABASE.map((r) => [
    `### ${r.name} (${r.brand})`,
    `Category: ${r.category}`,
    `Head: ${r.head_size} | Weight: ${r.weight} | Balance: ${r.balance} | Stiffness: ${r.stiffness}`,
    `String pattern: ${r.string_pattern} | Price: ${r.price_range}`,
    `Best for levels: ${r.best_for_level.join(", ")}`,
    `Best for styles: ${r.best_for_style.join(", ")}`,
    `Best for priorities: ${r.best_for_priority.join(", ")}`,
    `Age notes: ${r.age_sweet_spot}`,
    `Gender notes: ${r.gender_notes}`,
    `First racket suitable: ${r.first_racket_suitable ? "Yes" : "No"}`,
    `Health/arm notes: ${r.health_warning}`,
    `Strengths: ${r.strengths}`,
    `Weaknesses: ${r.weaknesses}`,
    `Ideal profile: ${r.ideal_profile}`,
    `Not ideal for: ${r.not_ideal_for}`,
    ...(r.famous_users ? [`Used by: ${r.famous_users}`] : []),
    "",
  ].join("\n")).join("\n");
}
