type RecommendedString = {
  name: string;
  type: string;
  tension_range_kg: string;
  why: string;
};

export type RacketEntry = {
  name: string;
  brand: string;
  category: string;
  head_size_sq_in: number;
  weight_g: number;
  balance_mm: number;
  stiffness_ra: number;
  string_pattern: string;
  price_range_eur: string;
  best_for_style: string[];
  best_for_priority: string[];
  best_for_level: string[];
  age_sweet_spot: string;
  gender_notes: string;
  first_racket_suitable: boolean;
  health_warning: string;
  strengths: string;
  weaknesses: string;
  ideal_profile: string;
  not_ideal_for: string;
  famous_users: string;
  similar_alternatives: string[];
  recommended_string: RecommendedString;
};

export const RACKET_DATABASE: RacketEntry[] = [
  {
    name: "Babolat Pure Aero 2026",
    brand: "Babolat",
    category: "Spin & Power",
    head_size_sq_in: 100,
    weight_g: 300,
    balance_mm: 320,
    stiffness_ra: 66,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["aggressive baseliner", "defensive counter-puncher"],
    best_for_priority: ["spin", "power"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+. The 300g weight is quite versatile. May be too demanding for 50+ or juniors under 16 because of its stiffness.",
    gender_notes: "Unisex. Popular on both ATP and WTA tours.",
    first_racket_suitable: true,
    health_warning: "Despite the fact the 2026 version has NF2 Tech and is more comfortable than the predecessor, players with elbow, wrist or shoulder concerns should look elsewhere.",
    strengths: "Provides good spin and power with a decent control due to a tighter string pattern compared to the first iterations of the racket (2017 and 2019 versions). New beam design cuts through the air for fast racket head speed. Forgiving on off-center hits for its weight class and mass distribution.",
    weaknesses: "Can feel stiff and muted to touch-oriented players. Not ideal for serve-and-volley or net play. The spin-focused design can make flat shots feel less controlled though in the last two versions (2023 and 2026) it has been massively improved.",
    ideal_profile: "An intermediate-to-advanced aggressive baseliner and counter-puncher aged 18-55+ who wants to dominate rallies with heavy topspin. Also works for defensive counter-punchers who use topspin lobs and passing shots to defend and get back to the point.",
    not_ideal_for: "Jouniors (too stiff and heavy), serve-and-volley players (lacks precision at net), players with arm issues (too stiff), seniors (stiffness might be an issue for joints).",
    famous_users: "Rafael Nadal (retired), Alex Michelsen, Adrian Mannarino",
    similar_alternatives: ["Head Extreme MP", "Yonex VCORE 100"],
    recommended_string: {
      name: "Babolat RPM Blast",
      type: "Polyester",
      tension_range_kg: "20-22",
      why: "The classic pairing. RPM Blast's spin potential complements the Pure Aero's aerodynamic frame, maximizing topspin generation. The polyester construction gives enough control to balance the racket's inherent power.",
    },
  },
  {
    name: "Babolat Pure Aero 98 2026",
    brand: "Babolat",
    category: "Spin & Control",
    head_size_sq_in: 98,
    weight_g: 305,
    balance_mm: 325,
    stiffness_ra: 66,
    string_pattern: "16x20",
    price_range_eur: "150-200",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["spin", "control"],
    best_for_level: ["upper-intermidiate", "advanced"],
    age_sweet_spot: "18-55+. Demanding frame that requires good fitness and technique.",
    gender_notes: "More popular among male players due to its weight and weight distribution.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. Better than the 100 model for arm issues but still not the most arm-friendly frame. Despite the fact the 2026 version has NF2 Tech and is more comfortable than the predecessor, players with elbow, wrist or shoulder concerns should look elsewhere.",
    strengths: "The best of both worlds — Pure Aero's spin generation in a more controlled, precise package. Smaller head size and thinner beam give better feel and placement. Great for advanced players who want a perfect blend of power, spin AND precision.",
    weaknesses: "Smaller sweet spot than the 100 sq in version. Less power — you need to generate your own. Heavier swing weight and lots of mass in the throat demand good fitness and racket head speed.",
    ideal_profile: "An advanced all-court player or aggressive baseliner who loves the Pure Aero's spin but wants more control and precision. A stepping stone for players upgrading from the Pure Aero 100.",
    not_ideal_for: "Beginners, intermediates, players wanting easy power, anyone with arm issues.",
    famous_users: "Carlos Alcaraz, Felix Auger-Aliassime, Holger Rune",
    similar_alternatives: ["Head Extreme Pro", "Tecnifibre 305s"],
    recommended_string: {
      name: "Babolat RPM Blast",
      type: "Polyester",
      tension_range_kg: "20-23",
      why: "The classic pairing. RPM Blast's spin potential complements the Pure Aero's aerodynamic frame, maximizing topspin generation. The polyester construction gives enough control to balance the racket's inherent power.",
    },
  },
  {
    name: "Babolat Pure Aero Lite 2026",
    brand: "Babolat",
    category: "Spin & Power (Lightweight)",
    head_size_sq_in: 100,
    weight_g: 270,
    balance_mm: 335,
    stiffness_ra: 65,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["aggressive baseliner", "defensive counter-puncher"],
    best_for_priority: ["spin", "power"],
    best_for_level: ["beginner", "intermediate"],
    age_sweet_spot: "All ages. Light enough for juniors 14+, seniors 55+, and anyone who finds the 300g and Team versions too heavy. The only concern is its stiffness and lack of stability due to lower weight.",
    gender_notes: "Very popular among female players, juniors and seniors.",
    first_racket_suitable: true,
    health_warning: "Same stiffness as the full Pure Aero (70+ RA). Players with wrist, elbow or shoulder issues should still consider softer frames.",
    strengths: "More spin due to a lighter weight and more open string pattern compared to the regular 300g version. Head-heavy balance compensates for the lower weight by adding stability on impact. Great for developing players who want to learn topspin technique. It's a platform racket and can easily be customized.",
    weaknesses: "Less stable than the full-weight version against heavy hitters.",
    ideal_profile: "A beginner or intermediate player of any age and gender who wants the Pure Aero's spin DNA but needs a lighter frame. Perfect for women, juniors and seniors. Or for someone who likes to customize their frames.",
    not_ideal_for: "Advanced players (not enough stability), powerful hitters (lacks explosive power).",
    famous_users: "Popular among WTA players and club competitors",
    similar_alternatives: ["Head Extreme MP L", "Yonex VCORE 100L"],
    recommended_string: {
      name: "Babolat RPM Blast",
      type: "Polyester",
      tension_range_kg: "20-23",
      why: "The classic pairing. RPM Blast's spin potential complements the Pure Aero's aerodynamic frame, maximizing topspin generation.",
    },
  },
  {
    name: "Babolat Pure Aero Team 2026",
    brand: "Babolat",
    category: "Spin & Power",
    head_size_sq_in: 100,
    weight_g: 285,
    balance_mm: 330,
    stiffness_ra: 70,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["aggressive baseliner", "defensive counter-puncher"],
    best_for_priority: ["spin", "power"],
    best_for_level: ["beginner", "intermediate"],
    age_sweet_spot: "All ages. Light enough for juniors 14+, seniors 55+, and anyone who finds 300g too heavy. The only concern is stiffness.",
    gender_notes: "Very popular among female players, juniors and seniors.",
    first_racket_suitable: true,
    health_warning: "Same stiffness as the full Pure Aero (70+ RA). Players with wrist, elbow or shoulder issues should still consider softer frames.",
    strengths: "All the spin benefits of the Pure Aero in a lighter, more maneuverable package. Head-heavy balance compensates for the lower weight by adding stability on impact. Great for developing players who want to learn topspin technique. Can easily be customized.",
    weaknesses: "Less stable than the full-weight version against heavy hitters.",
    ideal_profile: "A beginner or intermediate player of any age and gender who wants the Pure Aero's spin DNA but needs a lighter frame. Perfect for women, juniors and seniors. Or for someone who likes to customize their frames.",
    not_ideal_for: "Advanced players (not enough stability), powerful hitters (lacks explosive power).",
    famous_users: "Popular among WTA players and club competitors",
    similar_alternatives: ["Head Extreme MP L", "Yonex VCORE 100L"],
    recommended_string: {
      name: "Babolat RPM Blast",
      type: "Polyester",
      tension_range_kg: "20-23",
      why: "The classic pairing. RPM Blast's spin potential complements the Pure Aero's aerodynamic frame, maximizing topspin generation.",
    },
  },
  {
    name: "Babolat Pure Drive",
    brand: "Babolat",
    category: "Power",
    head_size_sq_in: 100,
    weight_g: 300,
    balance_mm: 320,
    stiffness_ra: 72,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["aggressive baseliner", "defensive counter-puncher"],
    best_for_priority: ["power"],
    best_for_level: ["beginner", "intermediate", "upper-intermediate", "advanced"],
    age_sweet_spot: "All ages. A versatile frame that suits a wide range of players regardless of age, gender, or skill level.",
    gender_notes: "Unisex. Extremely popular at club and professional level for both men and women.",
    first_racket_suitable: true,
    health_warning: "Despite the fact the 2025 version has NF2 Tech and is more comfortable than the predecessor, it's still one of the stiffest frames on the market. If a player is sensitive to stiffness it can lead to wrist pain, tennis elbow or shoulder pain.",
    strengths: "Controlled power. The Pure Drive offers maximum ball speed with less effort. Excellent for aggressive returns and deep baseline rallies. Excellent serving frame.",
    weaknesses: "The stiffest Babolat frame. With a wrong string setup can feel boardy and lack feel. Spin generation is decent but not at Pure Aero level.",
    ideal_profile: "A versatile frame that suits a wide range of players regardless of age, gender, or skill level.",
    not_ideal_for: "Anyone with arm issues and sensitivity towards stiffness, finesse players, serve-and-volley players.",
    famous_users: "GIOVANNI MPETSHI PERRICARD, JERRY SHANG",
    similar_alternatives: ["Wilson Ultra 100", "Yonex EZONE 100"],
    recommended_string: {
      name: "Dunlop Explosive Speed",
      type: "Polyester",
      tension_range_kg: "20-22",
      why: "It's a powerful frame and requires a stiff polyester to tame the power. With health issues, it's better to pair it with a soft cross string, either a multifilament or natural gut. If money is a concern, synthetic gut is a good budget-friendly alternative to natural gut for the cross string. The Explosive Speed's spin potential also complements the Pure Drive's power, helping to add some bite to the shots without sacrificing too much control.",
    },
  },
  {
    name: "Babolat Pure Drive 98 2025",
    brand: "Babolat",
    category: "Power & Control",
    head_size_sq_in: 98,
    weight_g: 305,
    balance_mm: 325,
    stiffness_ra: 73,
    string_pattern: "16x20",
    price_range_eur: "150-200",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["power", "control"],
    best_for_level: ["advanced"],
    age_sweet_spot: "20-35. Demanding frame for fit, technically proficient players.",
    gender_notes: "More popular among male advanced players.",
    first_racket_suitable: false,
    health_warning: "Still quite stiff. Not arm-friendly.",
    strengths: "Pure Drive power in a more controlled package. Smaller head gives better precision. Good for advanced players who hit flat and want explosive pace with directional control.",
    weaknesses: "Less forgiving than the 100. Demands clean technique. Still stiff.",
    ideal_profile: "An advanced all-court player who wants Pure Drive's power but with more surgical precision.",
    not_ideal_for: "Beginners, intermediates, players with arm issues.",
    famous_users: "GIOVANNI MPETSHI PERRICARD, JERRY SHANG",
    similar_alternatives: ["Babolat Pure Aero 98"],
    recommended_string: {
      name: "Dunlop Explosive Speed",
      type: "Polyester",
      tension_range_kg: "20-22",
      why: "It's a powerful frame and requires a stiff polyester to tame the power. With health issues, it's better to pair it with a soft cross string, either a multifilament or natural gut. If money is a concern, synthetic gut is a good budget-friendly alternative to natural gut for the cross string. The Explosive Speed's spin potential also complements the Pure Drive's power, helping to add some bite to the shots without sacrificing too much control.",
    },
  },
  {
    name: "Babolat Pure Drive Lite 2025",
    brand: "Babolat",
    category: "Power",
    head_size_sq_in: 100,
    weight_g: 270,
    balance_mm: 330,
    stiffness_ra: 72,
    string_pattern: "16x19",
    price_range_eur: "200-250",
    best_for_style: ["aggressive baseliner", "defensive counter-puncher"],
    best_for_priority: ["power"],
    best_for_level: ["beginner"],
    age_sweet_spot: "All ages. A versatile frame that suits a wide range of players regardless of age, gender, or skill level.",
    gender_notes: "Unisex. Extremely popular at club and professional level for both men and women.",
    first_racket_suitable: true,
    health_warning: "Despite the fact the 2025 version has NF2 Tech and is more comfortable than the predecessor, it's still one of the stiffest frames on the market. If a player is sensitive to stiffness it can lead to wrist pain, tennis elbow or shoulder pain.",
    strengths: "Controlled power. The Pure Drive offers maximum ball speed with less effort. Excellent for aggressive returns and deep baseline rallies. Excellent serving frame.",
    weaknesses: "The stiffest Babolat frame. With a wrong string setup can feel boardy and lack feel. Spin generation is decent but not at Pure Aero level.",
    ideal_profile: "A versatile frame that suits a wide range of players regardless of age, gender, or skill level.",
    not_ideal_for: "Anyone with arm issues and sensitivity towards stiffness, finesse players, serve-and-volley players.",
    famous_users: "Previously used by many ATP/WTA players at various career stages",
    similar_alternatives: ["Wilson Ultra 100", "Yonex EZONE 100"],
    recommended_string: {
      name: "Dunlop Explosive Speed",
      type: "Polyester",
      tension_range_kg: "20-22",
      why: "It's a powerful frame and requires a stiff polyester to tame the power. With health issues, it's better to pair it with a soft cross string, either a multifilament or natural gut. If money is a concern, synthetic gut is a good budget-friendly alternative to natural gut for the cross string. The Explosive Speed's spin potential also complements the Pure Drive's power, helping to add some bite to the shots without sacrificing too much control.",
    },
  },
  {
    name: "Babolat Pure Drive Team 2025",
    brand: "Babolat",
    category: "Power",
    head_size_sq_in: 100,
    weight_g: 285,
    balance_mm: 320,
    stiffness_ra: 72,
    string_pattern: "16x19",
    price_range_eur: "200-250",
    best_for_style: ["aggressive baseliner", "defensive counter-puncher"],
    best_for_priority: ["power"],
    best_for_level: ["beginner", "intermediate"],
    age_sweet_spot: "All ages. A versatile frame that suits a wide range of players regardless of age, gender, or skill level.",
    gender_notes: "Unisex. Extremely popular at club and professional level for both men and women.",
    first_racket_suitable: true,
    health_warning: "Despite the fact the 2025 version has NF2 Tech and is more comfortable than the predecessor, it's still one of the stiffest frames on the market. If a player is sensitive to stiffness it can lead to wrist pain, tennis elbow or shoulder pain.",
    strengths: "Controlled power. The Pure Drive offers maximum ball speed with less effort. Excellent for aggressive returns and deep baseline rallies. Excellent serving frame.",
    weaknesses: "The stiffest Babolat frame. With a wrong string setup can feel boardy and lack feel. Spin generation is decent but not at Pure Aero level.",
    ideal_profile: "A versatile frame that suits a wide range of players regardless of age, gender, or skill level.",
    not_ideal_for: "Anyone with arm issues and sensitivity towards stiffness, finesse players, serve-and-volley players.",
    famous_users: "Previously used by many ATP/WTA players at various career stages",
    similar_alternatives: ["Wilson Ultra 100", "Yonex EZONE 100"],
    recommended_string: {
      name: "Dunlop Explosive Speed",
      type: "Polyester",
      tension_range_kg: "20-22",
      why: "It's a powerful frame and requires a stiff polyester to tame the power. With health issues, it's better to pair it with a soft cross string, either a multifilament or natural gut. If money is a concern, synthetic gut is a good budget-friendly alternative to natural gut for the cross string. The Explosive Speed's spin potential also complements the Pure Drive's power, helping to add some bite to the shots without sacrificing too much control.",
    },
  },
  {
    name: "Babolat Pure Strike 98 16x19 2024",
    brand: "Babolat",
    category: "Control & Precision",
    head_size_sq_in: 98,
    weight_g: 305,
    balance_mm: 320,
    stiffness_ra: 68,
    string_pattern: "16x19",
    price_range_eur: "210-260",
    best_for_style: ["aggressive baseliner", "all-court"],
    best_for_priority: ["control", "spin", "power"],
    best_for_level: ["upper-intermdiate", "advanced"],
    age_sweet_spot: "18-55+. Suits fit players with developed technique.",
    gender_notes: "Unisex. Used on both tours.",
    first_racket_suitable: true,
    health_warning: "Quite high stiffness (68 RA). Reasonable for most players but those with chronic arm issues should consider softer frames. Hight swingweight might be taxating on the arm, wrist and shoulder",
    strengths: "The precision instrument of Babolat's lineup. Clean, modern feel with excellent feedback on every shot. Great blend of control and spin from the 16x19 pattern. Versatile enough for aggressive baseliners and all-court players.",
    weaknesses: "Less raw power than the Pure Drive or Pure Aero. Demands good technique. Smaller sweet spot and high swingweight.",
    ideal_profile: "An advanced aggressive baseliner or all-court player who values control and precision. The thinking player's Babolat — for those who place the ball rather than just hit it hard.",
    not_ideal_for: "Beginners, pure power seekers, players who need maximum forgiveness.",
    famous_users: "Dominic Thiem (previously), Cameron Norrie",
    similar_alternatives: ["Prince ATS Textreme Tour 98", "Wilson Blade 98 16x19", "Tecnifibre TF40 16x19"],
    recommended_string: {
      name: "Dunlop Explosive Speed",
      type: "Polyester",
      tension_range_kg: "20-22",
      why: "It's a powerful frame and requires a stiff polyester to tame the power. With health issues, it's better to pair it with a soft cross string, either a multifilament or natural gut. If money is a concern, synthetic gut is a good budget-friendly alternative to natural gut for the cross string. The Explosive Speed's spin potential also complements the Pure Drive's power, helping to add some bite to the shots without sacrificing too much control.",
    },
  },
  {
    name: "Babolat Pure Strike 100 16x20 2024",
    brand: "Babolat",
    category: "Control & Comfort",
    head_size_sq_in: 100,
    weight_g: 305,
    balance_mm: 320,
    stiffness_ra: 65,
    string_pattern: "16x20",
    price_range_eur: "200-250",
    best_for_style: ["all-court", "serve and volley"],
    best_for_priority: ["control"],
    best_for_level: ["beginner", "intermediate", "advanced"],
    age_sweet_spot: "18-55+. More forgiving than the 98, suitable for a wider range.",
    gender_notes: "Unisex. Good transition racket from intermediate to advanced.",
    first_racket_suitable: true,
    health_warning: "Moderate stiffness. More comfortable than the Pure Drive or Pure Aero with good control",
    strengths: "The comfortable Pure Strike. Larger head gives more forgiveness than the 98. Denser 16x20 pattern adds control and predictability Great middle ground between power and control.",
    weaknesses: "Not as precise as the 98 version. Can feel a bit unstable",
    ideal_profile: "An intermediate-to-advanced player who wants control and comfort without the demanding nature of the 98. Great for players stepping up from beginner rackets who want a serious frame that won't punish them.",
    not_ideal_for: "Pure spin players (16x20 reduces spin), heavy hitters (lacks stability in stock form).",
    famous_users: "",
    similar_alternatives: ["Yonex Percept 100, Head Gravity MP and Wilson Blade 100 v9"],
    recommended_string: {
      name: "Dunlop Explosive Speed",
      type: "Polyester",
      tension_range_kg: "20-22",
      why: "It's a powerful frame and requires a stiff polyester to tame the power. With health issues, it's better to pair it with a soft cross string, either a multifilament or natural gut. If money is a concern, synthetic gut is a good budget-friendly alternative to natural gut for the cross string. The Explosive Speed's spin potential also complements the Pure Strike's control, helping to add some bite to the shots without sacrificing too much control.",
    },
  },
  {
    name: "Babolat Pure Strike 98 18x20 2024",
    brand: "Babolat",
    category: "Control & Precision",
    head_size_sq_in: 98,
    weight_g: 305,
    balance_mm: 320,
    stiffness_ra: 68,
    string_pattern: "18x20",
    price_range_eur: "150-200",
    best_for_style: ["serve and volley", "all-court"],
    best_for_priority: ["control"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+. Demanding frame for technically complete players.",
    gender_notes: "More popular among male players with strong technique.",
    first_racket_suitable: false,
    health_warning: "Dense string pattern and weight demand good technique. Moderate on arm-friendliness.",
    strengths: "Maximum control for Babolat's lineup. The dense 18x20 pattern gives surgical precision on flat shots, slices, and volleys. The serve-and-volley player's Babolat. Excellent for players who come to the net.",
    weaknesses: "Least spin-friendly Babolat due to dense pattern. Demands you generate all your own power. Due to low net clearance, it offers very small margin for error.",
    ideal_profile: "An advanced serve-and-volley player or all-court player who prioritises placement over power. The thinking player's Babolat — for those who place the ball rather than just hit it hard.",
    not_ideal_for: "Spin-dependent players, beginners, intermediates, power seekers.",
    famous_users: "",
    similar_alternatives: ["Head Prestige MP", "Wilson Blade 98 18x20", "Tecnifibre TF40 18x20"],
    recommended_string: {
      name: "Solinco Confidential",
      type: "Polyester",
      tension_range_kg: "20-22",
      why: "It's a control frame witha a very dense string patter, this is why it requires a thin, spin friendly polyester to grab the ball and increase net clearance and launch angle.",
    },
  },
  {
    name: "Head Speed MP 2026",
    brand: "Head",
    category: "All-Court Performance",
    head_size_sq_in: 100,
    weight_g: 300,
    balance_mm: 320,
    stiffness_ra: 60,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["power", "spin"],
    best_for_level: ["intermediate", "upper-intermediate", "advanced"],
    age_sweet_spot: "20-55+. It's a very versatile frame that suits a wide range of players regardless of age.",
    gender_notes: "Unisex. Very popular among both male and female players at all levels.",
    first_racket_suitable: true,
    health_warning: "Lower stiffness (60 RA) makes it more arm-friendly than most performance frames. Reasonable for players with mild arm concerns.",
    strengths: "The most versatile racket in Head's lineup. Does everything well — baseline, net, serve. Auxetic technology gives excellent feel and feedback. Lower stiffness than competitors means better comfort without sacrificing performance. The complete all-court weapon.",
    weaknesses: "Doesn't excel in any single area the way specialised frames do. Less raw spin than the Extreme. Less raw power than stiffer frames, less control than Radical or Prestige. It's a jack of all trades, master of none frame.",
    ideal_profile: "An all-court player or aggressive baseliner who wants one racket that does everything well. The Swiss Army knife of tennis rackets.",
    not_ideal_for: "Pure spin seekers (Extreme is better), pure control seekers (Radical or Prestige are better).",
    famous_users: "Janick Sinner",
    similar_alternatives: ["Babolat Pure Strike 100 16x19", "Wilson Blade 100", "Yonex Percept 100"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent spin potential and above-average tension maintenance make it a natural match for the Speed MP's all-court character. High control with enough comfort to suit the frame's lower stiffness — the two complement each other well.",
    },
  },
  {
    name: "Head Speed Pro 2026",
    brand: "Head",
    category: "All-Court Performance",
    head_size_sq_in: 100,
    weight_g: 310,
    balance_mm: 310,
    stiffness_ra: 61,
    string_pattern: "18x20",
    price_range_eur: "150-200",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["control"],
    best_for_level: ["advanced"],
    age_sweet_spot: "20-40. Suits fit, technically proficient players.",
    gender_notes: "More popular among male players with strong technique.",
    first_racket_suitable: false,
    health_warning: "Dense string pattern and weight demand good technique. Moderate on arm-friendliness.",
    strengths: "Maximum control for the Speed lineup. The dense 18x20 pattern gives surgical precision on flat shots, slices, and volleys. Great feel and feedback. Rock-solid stable and plush. Excellent for players who want a more traditional, control-oriented setup.",
    weaknesses: "Least spin-friendly in the Speed family due to dense pattern. Demands you generate all your own power. Very small margin for error.",
    ideal_profile: "An advanced all-court player who prioritises placement over power. For those who want more control than the Speed MP while keeping the Speed's feel.",
    not_ideal_for: "Spin-dependent players, beginners, intermediates, power seekers.",
    famous_users: "",
    similar_alternatives: ["Yonex Percept 100D", "Head Gravity Pro"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent spin potential and above-average tension maintenance make it a natural match for the Speed MP's all-court character. High control with enough comfort to suit the frame's lower stiffness — the two complement each other well.",
    },
  },
  {
    name: "Head Speed MP L 2026",
    brand: "Head",
    category: "All-Court Performance",
    head_size_sq_in: 100,
    weight_g: 285,
    balance_mm: 325,
    stiffness_ra: 61,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["power", "spin"],
    best_for_level: ["beginner", "intermediate"],
    age_sweet_spot: "All ages. A lighter, more accessible version of the Speed MP.",
    gender_notes: "Unisex. Very popular among transition players and juniors.",
    first_racket_suitable: true,
    health_warning: "Comfortable frame, low stiffness (61 RA). Good for players with arm concerns.",
    strengths: "Lighter, more maneuverable version of the Speed MP. Keeps the excellent feel and feedback while being easier to swing for longer periods. Great for improving players.",
    weaknesses: "Lacks the stability and plow-through of the heavier Speed MP version. Can be pushed around by heavy hitters.",
    ideal_profile: "An intermediate player or a developing junior who wants the Speed's versatility in a lighter, easier-to-handle package.",
    not_ideal_for: "Advanced players needing heavy stability, power hitters seeking maximum plow-through.",
    famous_users: "",
    similar_alternatives: ["Wilson Clash 100L", "Yonex EZONE 100L"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent spin potential and above-average tension maintenance make it a natural match for the Speed MP's all-court character. High control with enough comfort to suit the frame's lower stiffness — the two complement each other well.",
    },
  },
  {
    name: "Head Extreme MP 2022",
    brand: "Head",
    category: "Spin & Power",
    head_size_sq_in: 100,
    weight_g: 300,
    balance_mm: 320,
    stiffness_ra: 66,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["aggressive baseliner"],
    best_for_priority: ["spin", "power"],
    best_for_level: ["beginner", "intermediate", "upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. Very popular among baseline players.",
    first_racket_suitable: true,
    health_warning: "Stiff frame. Players with history of arm issues should be careful.",
    strengths: "The spin machine of Head's lineup. Generates massive topspin and easy power. Lively feel makes it great for hitting heavy baseline shots.",
    weaknesses: "Can be too lively/unpredictable for flat hitters. Not as precise or controlled as the Speed or Prestige lines.",
    ideal_profile: "An aggressive baseliner who relies on topspin and heavy groundstrokes to dictate points. The racket for players who want to dominate from the back of the court.",
    not_ideal_for: "Finesse players, serve-and-volley specialists, players needing maximum control.",
    famous_users: "M. Berrettini, A. Davidovich Fokina, J. Struff, B. Krejcikova",
    similar_alternatives: ["Pure Aero", "Pure Drive"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent spin potential and above-average tension maintenance make it a natural match for the Speed MP's all-court character. High control with enough comfort to suit the frame's lower stiffness — the two complement each other well.",
    },
  },
  {
    name: "Head Extreme Pro 2024",
    brand: "Head",
    category: "Spin & Power",
    head_size_sq_in: 98,
    weight_g: 305,
    balance_mm: 315,
    stiffness_ra: 64,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["aggressive baseliner"],
    best_for_priority: ["spin", "power"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. Very popular among baseline players.",
    first_racket_suitable: true,
    health_warning: "",
    strengths: "Good blend of spin and control. The spin machine of Head's lineup.",
    weaknesses: "Might feel a bit low powered and unstable at times.",
    ideal_profile: "A finesse player who relies on control, ball placement and ball control via spin.",
    not_ideal_for: "Aggressive baseliners who rely on heavy spin to damage their opponents.",
    famous_users: "M. Berrettini, A. Davidovich Fokina, J. Struff, B. Krejcikova",
    similar_alternatives: ["Pure Aero 98", "Yonex Vcore 98"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent spin potential and above-average tension maintenance make it a natural match for the Speed MP's all-court character. High control with enough comfort to suit the frame's lower stiffness — the two complement each other well.",
    },
  },
  {
    name: "Head Gravity MP 2025",
    brand: "Head",
    category: "Control & Comfort",
    head_size_sq_in: 100,
    weight_g: 295,
    balance_mm: 325,
    stiffness_ra: 57,
    string_pattern: "16x20",
    price_range_eur: "150-200",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["control", "comfort"],
    best_for_level: ["beginner", "intermediate", "upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. Popular among players who value feel.",
    first_racket_suitable: true,
    health_warning: "",
    strengths: "One of the most comfortable rackets on the market. Teardrop head shape provides a generous, forgiving sweet spot. Excellent touch and feel, great for drop shots and finesse play.",
    weaknesses: "Can feel a bit soft or muted for players who prefer a crisp, stiff response. Lower raw power levels compared to the Speed or Extreme lines.",
    ideal_profile: "Players who prioritize feel, comfort, and control over raw power. Great for finesse players who love to manipulate the ball.",
    not_ideal_for: "Players who need an explosive, stiff frame for easy power.",
    famous_users: "Alexander Zverev",
    similar_alternatives: ["Wilson Clash 100", "Yonex Percept 100"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent spin potential and above-average tension maintenance make it a natural match for the Speed MP's all-court character. High control with enough comfort to suit the frame's lower stiffness — the two complement each other well.",
    },
  },
  {
    name: "Head Gravity Pro 2025",
    brand: "Head",
    category: "Control & Comfort",
    head_size_sq_in: 100,
    weight_g: 315,
    balance_mm: 310,
    stiffness_ra: 59,
    string_pattern: "18x20",
    price_range_eur: "150-200",
    best_for_style: ["aggressive baseliner", "counterpuncher"],
    best_for_priority: ["control", "feel", "precision"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. Popular among advanced players who value touch and precision.",
    first_racket_suitable: false,
    health_warning: "Heavy frame at 315g with a low power level. Players with existing arm, elbow or shoulder issues should be cautious — prolonged use without proper technique and conditioning may aggravate injury.",
    strengths: "Exceptional control and feel. The 18x20 string pattern delivers pinpoint precision and outstanding touch. One of the most arm-friendly frames on the market thanks to its low stiffness (59 RA). Teardrop head shape rewards well-timed, clean ball striking.",
    weaknesses: "Demands a full, clean swing to get the best out of it. Low power ceiling means players who rely on the racket for free power will struggle. The dense string pattern produces less spin than 16x19 alternatives.",
    ideal_profile: "An advanced player with a technically sound game who values precision, touch, and feel over raw power. Perfect for players who like to control rallies with placement and slice rather than brute force.",
    not_ideal_for: "Beginners and intermediate players who need power assistance. Heavy topspin baseliners who need an open string pattern.",
    famous_users: "Alexander Zverev",
    similar_alternatives: ["Wilson Blade 100", "Yonex Percept 100"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent spin potential and above-average tension maintenance make it a natural match for the Gravity Pro's precision-oriented character. High control with enough comfort to complement the frame's low stiffness.",
    },
  },
  {
    name: "Head Gravity Tour 2025",
    brand: "Head",
    category: "Control & Comfort",
    head_size_sq_in: 98,
    weight_g: 305,
    balance_mm: 320,
    stiffness_ra: 59,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["aggressive baseliner"],
    best_for_priority: ["control", "feel", "precision"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. Popular among advanced players who value touch and precision.",
    first_racket_suitable: false,
    health_warning: "",
    strengths: "Excellent blend of control, feel and spin. The 16x19 open pattern gives it more spin potential than the Gravity Pro while retaining the teardrop head shape's signature touch and precision. Very comfortable at 59 RA.",
    weaknesses: "Demands clean, confident ball striking. Low power output requires a full swing to generate pace. Not forgiving enough for players still developing their technique.",
    ideal_profile: "An upper-intermediate to advanced player who wants the Gravity line's feel and control in a slightly more spin-friendly package than the Pro. Great for baseliners who value placement and ball control over raw power.",
    not_ideal_for: "Beginners and intermediate players who need power assistance. Players who rely on the racket for free pace.",
    famous_users: "",
    similar_alternatives: ["Wilson Blade 98", "Yonex Percept 97"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent spin potential and above-average tension maintenance make it a natural match for the Gravity Tour's precision-oriented character. High control with enough comfort to complement the frame's low stiffness.",
    },
  },
  {
    name: "Head Radical MP 2025",
    brand: "Head",
    category: "Control",
    head_size_sq_in: 98,
    weight_g: 300,
    balance_mm: 320,
    stiffness_ra: 65,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["all-court player", "serve & volley"],
    best_for_priority: ["control", "precision", "versatility"],
    best_for_level: ["intermediate", "upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. One of the most popular all-court frames across all levels.",
    first_racket_suitable: false,
    health_warning: "Stiffer frame at 65 RA. Players with existing arm, elbow or shoulder issues should be cautious — the higher stiffness transmits more shock and vibration compared to softer alternatives.",
    strengths: "Versatile all-court performer with a solid balance of control and feel. The 16x19 pattern and hybrid beam deliver consistent response with good plow-through. Accessible enough for upper-intermediate players yet capable enough for advanced.",
    weaknesses: "Low power output demands a full, confident swing to generate pace. The 16x19 pattern produces less spin than more open alternatives. The 65 RA stiffness is less arm-friendly than more flexible frames.",
    ideal_profile: "An intermediate to advanced all-court player who wants a versatile, control-oriented frame that works well from all areas of the court. Suits players with complete games who approach the net and vary their play.",
    not_ideal_for: "Players with arm or elbow sensitivity. Players who rely on the racket for free power or spin.",
    famous_users: "Flavio Cobolli, T. Fritz, N. Borges, M. Arnaldi",
    similar_alternatives: ["Wilson Blade 98 16x19"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "21-23",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent control and above-average tension maintenance make it a natural match for the Radical MP's precision-oriented character. High control with enough comfort to complement the frame's stiffness.",
    },
  },
  {
    name: "Head Radical Pro 2025",
    brand: "Head",
    category: "Control",
    head_size_sq_in: 98,
    weight_g: 315,
    balance_mm: 315,
    stiffness_ra: 64,
    string_pattern: "16x19",
    price_range_eur: "180-230",
    best_for_style: ["all-court player", "serve & volley"],
    best_for_priority: ["control", "precision", "feel"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. A serious player's tool favoured by advanced all-court competitors.",
    first_racket_suitable: false,
    health_warning: "Stiffish frame at 64 RA combined with heavier weight at 315g. Players with existing arm, elbow or shoulder issues should be cautious — the stiffness transmits more shock and vibration compared to softer alternatives.",
    strengths: "A more demanding, heavier version of the Radical MP that rewards precise, confident ball striking. Greater plow-through and stability than the MP thanks to the extra weight. Excellent control and feel for advanced players who generate their own power. The 16x19 pattern offers good variety from the baseline and net.",
    weaknesses: "Low power output demands a full, confident swing to generate pace. The 16x19 pattern produces less spin than more open alternatives. Heavy and stiffish frame is unforgiving of off-centre hits and poor technique.",
    ideal_profile: "An advanced all-court player with a complete, technically polished game who wants maximum control and feel. Suits players who construct points through placement and variety rather than brute force, and who are comfortable approaching the net.",
    not_ideal_for: "Beginners and intermediate players who need power assistance. Players with arm or elbow sensitivity. Players who rely on the racket for free power.",
    famous_users: "Flavio Cobolli, T. Fritz, N. Borges, M. Arnaldi",
    similar_alternatives: ["Wilson Blade 98 16x19"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "21-23",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent control and above-average tension maintenance make it a natural match for the Radical Pro's precision-oriented character. High control with enough comfort to complement the frame's stiffness.",
    },
  },
  {
    name: "Head Radical Team 2025",
    brand: "Head",
    category: "Control",
    head_size_sq_in: 102,
    weight_g: 280,
    balance_mm: 320,
    stiffness_ra: 63,
    string_pattern: "16x19",
    price_range_eur: "100-150",
    best_for_style: ["all-court player"],
    best_for_priority: ["control", "maneuverability", "feel"],
    best_for_level: ["beginner", "intermediate"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. A popular entry point into the Radical line for beginners and intermediate players.",
    first_racket_suitable: true,
    health_warning: "",
    strengths: "Light and easy to maneuver, making it an excellent choice for beginners and intermediate players. The 102 in² head and wider beam provide a generous sweet spot and good forgiveness on off-centre hits. A great way to get into a control-oriented frame without the demands of a heavier racket.",
    weaknesses: "Less stable than the heavier MP and Pro on hard-hit balls. Not suited for advanced players who need more plow-through and precision.",
    ideal_profile: "A beginner or intermediate all-court player looking for an easy-to-use, forgiving frame that still rewards developing technique. Suits players transitioning from a starter racket who want more control and feel without being overwhelmed by a heavy, demanding frame.",
    not_ideal_for: "Advanced players who need stability and plow-through.",
    famous_users: "",
    similar_alternatives: ["Wilson Blade 102"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent control and above-average tension maintenance make it a natural match for the Radical Team's precision-oriented character. High control with enough comfort to complement the frame's relatively modest stiffness.",
    },
  },
  {
    name: "Head Prestige MP 2025",
    brand: "Head",
    category: "Control",
    head_size_sq_in: 99,
    weight_g: 310,
    balance_mm: 320,
    stiffness_ra: 66,
    string_pattern: "18x19",
    price_range_eur: "150-200",
    best_for_style: ["all-court player", "serve & volley"],
    best_for_priority: ["control", "precision", "feel"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. A legendary control frame favoured by advanced players who prioritise precision above all else.",
    first_racket_suitable: false,
    health_warning: "",
    strengths: "One of the most precise and controlled frames on the market. The ultra-dense 18x19 string pattern delivers exceptional ball placement, pinpoint control and outstanding feel. Despite its 66 RA rating, the classic plush layup makes it a surprisingly comfortable and arm-friendly frame. High twistweight of 15.6 provides excellent stability on off-centre hits. A true player's frame with a long, distinguished history at the highest level.",
    weaknesses: "The 18x19 pattern severely limits spin production. Demands technically sound, confident ball striking — unforgiving of inconsistent or rushed swings.",
    ideal_profile: "An advanced all-court player with a technically polished game who values pinpoint precision and feel over spin. Ideal for players who construct points through placement, slice and variety, and who are comfortable approaching the net.",
    not_ideal_for: "Beginners and intermediate players. Heavy topspin baseliners who rely on an open string pattern.",
    famous_users: "Novak Djokovic (historical), Marat Safin (historical)",
    similar_alternatives: ["Yonex Percept 100D"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "21-23",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent control and above-average tension maintenance make it a natural match for the Prestige MP's precision-oriented character. High control with enough comfort to complement the frame's plush feel.",
    },
  },
  {
    name: "Head Prestige MP L 2025",
    brand: "Head",
    category: "Control",
    head_size_sq_in: 99,
    weight_g: 300,
    balance_mm: 315,
    stiffness_ra: 61,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["all-court player"],
    best_for_priority: ["control", "precision", "feel"],
    best_for_level: ["intermediate", "upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. A favourite among intermediate to advanced players who like to customise their setup and dial in their racket precisely.",
    first_racket_suitable: false,
    health_warning: "",
    strengths: "An outstanding platform racket for players who love to customise. The lighter 300g base weight and lower swingweight leave plenty of room to add lead tape and fine-tune balance, swingweight and plow-through to personal taste. The softer 61 RA flex combined with the classic plush Prestige layup delivers exceptional comfort and feel. The 16x19 pattern adds versatility and variety to the shot selection.",
    weaknesses: "Out of the box, the lighter weight and lower swingweight provide less plow-through and stability than the standard MP. Demands a technically sound game — not forgiving for players still developing consistency.",
    ideal_profile: "An intermediate to advanced all-court player who wants the Prestige's legendary control and feel in a lighter, more customisable package. Perfect for players who enjoy tinkering with lead tape and tuning their racket to exact specifications.",
    not_ideal_for: "Beginners who need a ready-to-play, forgiving frame. Players who want a setup that works well straight out of the box without customisation.",
    famous_users: "M. Cilic, F. Cerundolo, D. Köpfer, A. Karatsev",
    similar_alternatives: ["Yonex Percept 100", "Wilson Blade 100", "Babolat Pure Strike 100", "Head Gravity Tour"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "21-23",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent control and above-average tension maintenance make it a natural match for the Prestige MP L's precision-oriented character. High control with enough comfort to complement the frame's plush feel.",
    },
  },
  {
    name: "Head Prestige Pro 2025",
    brand: "Head",
    category: "Control",
    head_size_sq_in: 98,
    weight_g: 320,
    balance_mm: 310,
    stiffness_ra: 58,
    string_pattern: "18x20",
    price_range_eur: "180-230",
    best_for_style: ["all-court player", "serve & volley"],
    best_for_priority: ["control", "precision", "feel"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. A serious player's precision tool for advanced all-court competitors who demand the ultimate connection between player and racket.",
    first_racket_suitable: false,
    health_warning: "",
    strengths: "The pinnacle of the Prestige line. Features Head's Auxetic 2.0 technology for a sensational feel that creates an ultimate connection between player and racket. Despite its 320g weight and ultra-dense 18x20 pattern, the remarkably soft 58 RA flex delivers exceptional comfort and touch. Outstanding control and precision with superb plow-through thanks to the heavier frame weight.",
    weaknesses: "The 18x20 string pattern severely limits spin production. Demands technically polished, confident ball striking — highly unforgiving of rushed or inconsistent swings. Heavy frame requires a full, well-conditioned swing.",
    ideal_profile: "An advanced all-court player with a complete, technically polished game who wants the absolute maximum in control, feel and precision. Ideal for players who construct points through placement, variety and slice, and who are comfortable at the net.",
    not_ideal_for: "Beginners and intermediate players. Heavy topspin baseliners who rely on an open string pattern. Players who prefer a lighter, more manoeuvrable frame.",
    famous_users: "M. Cilic, F. Cerundolo, D. Köpfer, A. Karatsev",
    similar_alternatives: ["Head Radical Pro", "Head Gravity Pro"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "21-23",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent control and above-average tension maintenance make it a natural match for the Prestige Pro's precision-oriented character. High control with enough comfort to complement the frame's plush Auxetic feel.",
    },
  },
  {
    name: "Head Prestige Tour 2025",
    brand: "Head",
    category: "Control",
    head_size_sq_in: 95,
    weight_g: 315,
    balance_mm: 315,
    stiffness_ra: 62,
    string_pattern: "16x19",
    price_range_eur: "180-230",
    best_for_style: ["all-court player", "serve & volley"],
    best_for_priority: ["control", "precision", "feel"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. Built for technical tournament players who want a modern precision frame with sensational feel.",
    first_racket_suitable: false,
    health_warning: "",
    strengths: "Developed for technical tournament players who want to play exactly the way they want. Features Head's Auxetic 2.0 technology for a sensational feel and ultimate connection between player and racket. The smallest head in the Prestige lineup at 95 in² delivers pinpoint modern precision. The 16x19 pattern offers more versatility than the Pro's 18x20, balancing control with shot variety.",
    weaknesses: "The 95 in² head is extremely unforgiving of off-centre hits — demands technically polished, consistent ball striking. Not suited for players still developing their technique.",
    ideal_profile: "An advanced tournament player with a technically sound, complete game who wants maximum precision and feel in a modern, slightly more versatile Prestige package than the Pro.",
    not_ideal_for: "Beginners and intermediate players. Players who need a larger sweet spot or more forgiveness.",
    famous_users: "M. Cilic, F. Cerundolo, D. Köpfer, A. Karatsev",
    similar_alternatives: ["Head Radical Pro", "Head Gravity Pro", "Wilson Pro Staff 97 v14"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "21-23",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent control and above-average tension maintenance make it a natural match for the Prestige Tour's precision-oriented character. High control with enough comfort to complement the frame's plush Auxetic feel.",
    },
  },
  {
    name: "Head Boom MP 2026",
    brand: "Head",
    category: "Power & Comfort",
    head_size_sq_in: 100,
    weight_g: 295,
    balance_mm: 315,
    stiffness_ra: 62,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["aggressive baseliner", "all-court player"],
    best_for_priority: ["power", "comfort", "versatility"],
    best_for_level: ["beginner", "intermediate", "upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. Endorsed by Coco Gauff and Lorenzo Musetti. Designed for attacking players who want effortless power and enjoy the social and competitive side of the game.",
    first_racket_suitable: true,
    health_warning: "",
    strengths: "Combines explosive power with the ability to play delicate drop shots. Features Auxetic 2.0 technology for better ball feel, Hy-Bor material in the shaft for improved perceived stability and a solid impact feel, and an AI-developed string pattern for optimal power and ball contact. Directional Drilling technology adds comfort and touch. A versatile, confidence-inspiring frame for aggressive players across all levels.",
    weaknesses: "The wider 24mm beam and power-oriented character make it less suited for players who prioritise precision and feel over pace. Less control than the Prestige or Radical lines.",
    ideal_profile: "A beginner to advanced attacking player who wants effortless access to power and enjoys playing aggressively. Great for players who like to dictate play from the baseline and want a comfortable, modern frame that rewards offensive tennis.",
    not_ideal_for: "Players who prioritise control and feel above all else. Players seeking a precision instrument like the Prestige or Radical lines.",
    famous_users: "Coco Gauff, Lorenzo Musetti",
    similar_alternatives: ["Head Gravity MP", "Head Extreme MP", "Babolat Pure Aero 100", "Wilson Clash 100"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent control and above-average tension maintenance complement the Boom MP's power character well, adding precision and bite without sacrificing the frame's natural liveliness.",
    },
  },
  {
    name: "Head Boom Pro 2026",
    brand: "Head",
    category: "Power & Comfort",
    head_size_sq_in: 98,
    weight_g: 310,
    balance_mm: 310,
    stiffness_ra: 64,
    string_pattern: "16x19",
    price_range_eur: "180-230",
    best_for_style: ["aggressive baseliner", "all-court player"],
    best_for_priority: ["power", "control", "comfort"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. Endorsed by Coco Gauff and Lorenzo Musetti. The most control-oriented model in the Boom line, aimed at advanced and tournament players who attack.",
    first_racket_suitable: false,
    health_warning: "",
    strengths: "The most controlled and precise frame in the Boom series. Heavier and with a smaller 98 in² head than the Boom MP, it adds plow-through and extra precision while retaining the line's hallmark effortless power. Features Auxetic 2.0 for better ball feel, Hy-Bor in the shaft for perceived stability and a solid impact feel, and Directional Drilling for enhanced touch and comfort. A powerful yet controlled tool for attacking tournament players.",
    weaknesses: "Less forgiving than the Boom MP due to the smaller head and heavier weight. Not suited for players still developing their technique or those who need maximum comfort.",
    ideal_profile: "An advanced or tournament-level attacking player who wants the Boom line's effortless power with additional control and precision. Ideal for aggressive baseliners and all-court players who dictate points and demand a more demanding, tour-oriented frame.",
    not_ideal_for: "Beginners and intermediate players. Players who prioritise feel and precision over power.",
    famous_users: "Coco Gauff, Lorenzo Musetti",
    similar_alternatives: ["Head Gravity Pro", "Head Extreme Pro", "Wilson Clash 98"],
    recommended_string: {
      name: "Head Lynx Tour",
      type: "Co-Polyester",
      tension_range_kg: "21-23",
      why: "A medium-stiff co-poly with a 6-sided profile that sits between the softer Lynx and stiffer Hawk. Excellent control and above-average tension maintenance complement the Boom Pro's power character well, adding precision and bite without sacrificing the frame's natural liveliness.",
    },
  },
  {
    name: "Wilson Blade 100 v10",
    brand: "Wilson",
    category: "Control",
    head_size_sq_in: 100,
    weight_g: 300,
    balance_mm: 320,
    stiffness_ra: 61,
    string_pattern: "16x19",
    price_range_eur: "200-250",
    best_for_style: ["aggressive baseliner", "all-court player"],
    best_for_priority: ["control", "feel", "spin"],
    best_for_level: ["beginner", "intermediate", "upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. The tenth generation of one of tennis's most iconic control frames, redesigned for the modern game.",
    first_racket_suitable: true,
    health_warning: "",
    strengths: "Light at 300g and comfortable at 61 RA, making it easy to swing and handle for a wide range of players. The 100 in² head and 16x19 pattern produce noticeably more spin than smaller-head versions like the Blade 98, while still offering a decent level of precision and placement. A forgiving sweet spot makes it accessible for developing players while remaining capable enough for advanced ones. X-Loop technology in the shoulders adds stability without sacrificing feel.",
    weaknesses: "Less precise and less stable on hard-hit balls than the heavier Blade 98. Players who have developed a strong, full swing may eventually outgrow it and want more plow-through.",
    ideal_profile: "A beginner to advanced player looking for an easy-to-use, comfortable control frame with good spin potential. Works well for all-court players who want a forgiving racket that still rewards improving technique.",
    not_ideal_for: "Players who prioritise maximum precision and plow-through over accessibility. Players who prefer a stiffer, more powerful frame.",
    famous_users: "Belinda Bencic, Serena Williams (historical)",
    similar_alternatives: ["Head Speed MP", "Head Gravity Tour", "Head Radical MP", "Yonex Percept 100"],
    recommended_string: {
      name: "Luxilon ALU Power",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "The industry benchmark co-poly trusted by more tour players than any other string. Delivers exceptional control, durability and a crisp, precise feel that pairs naturally with the Blade 100's soft flex and open string pattern. Firm enough to add precision without overwhelming the frame's comfortable character.",
    },
  },
  {
    name: "Wilson Blade 98 16x19 v10",
    brand: "Wilson",
    category: "Control",
    head_size_sq_in: 98,
    weight_g: 305,
    balance_mm: 320,
    stiffness_ra: 61,
    string_pattern: "16x19",
    price_range_eur: "200-250",
    best_for_style: ["aggressive baseliner", "all-court player"],
    best_for_priority: ["control", "feel", "spin"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. The open-pattern variant of the iconic Blade 98 — more spin-friendly than the 18x20 version while retaining the line's signature control character.",
    first_racket_suitable: true,
    health_warning: "",
    strengths: "Comfortable and precise at 61 RA with a subtly tapered beam that improves head stability compared to previous generations. Industry-leading 3-degree torsional stability keeps the frame solid on off-centre hits. The 16x19 pattern produces good spin and pace, making it more aggressive than the 18x20 variant. Light enough at 305g to manoeuvre well while still providing good plow-through for an advanced player.",
    weaknesses: "More demanding than the Blade 100 — the smaller 98 in² head is less forgiving and requires consistent, technically sound ball striking. Less spin-friendly than wider frames with more open patterns.",
    ideal_profile: "An upper-intermediate to advanced all-court player who wants the Blade's trademark control and feel with the added aggression and spin of a 16x19 pattern. Suits players who hit with pace and topspin and want precision without sacrificing variety.",
    not_ideal_for: "Beginners and intermediate players who need a more forgiving frame. Players who prefer the tighter control of the 18x20 pattern.",
    famous_users: "Stefanos Tsitsipas, Ugo Humbert, David Goffin",
    similar_alternatives: ["Head Radical MP", "Head Speed MP", "Head Gravity Tour"],
    recommended_string: {
      name: "Luxilon ALU Power",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "The industry benchmark co-poly trusted by more tour players than any other string. Delivers exceptional control, durability and a crisp, precise feel that pairs naturally with the Blade 98's soft flex and open string pattern. Firm enough to add precision without overwhelming the frame's comfortable character.",
    },
  },
  {
    name: "Wilson Blade 98 18x20 v10",
    brand: "Wilson",
    category: "Control",
    head_size_sq_in: 98,
    weight_g: 305,
    balance_mm: 320,
    stiffness_ra: 61,
    string_pattern: "18x20",
    price_range_eur: "200-250",
    best_for_style: ["aggressive baseliner", "all-court player"],
    best_for_priority: ["control", "precision", "feel"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. The precision-focused, dense-pattern variant of the Blade 98 — maximum directional control and touch for players who generate their own pace.",
    first_racket_suitable: true,
    health_warning: "",
    strengths: "The densest, most precise version of the Blade 98. The 18x20 pattern delivers a firmer, more responsive stringbed with maximum directional control and a lower ball launch angle — ideal for players who flatten out their shots and dictate with placement. Industry-leading 3-degree torsional stability keeps the frame exceptionally neutral even on off-centre hits. Comfortable at 61 RA despite its precision-oriented character.",
    weaknesses: "The 18x20 pattern produces significantly less spin than the 16x19 version. Demands technically sound, consistent ball striking and a player who generates their own pace — not suited for those who rely on topspin or need help from the racket.",
    ideal_profile: "An advanced player with a technically polished, flat or semi-flat hitting style who wants the absolute maximum in directional control and precision. Ideal for players who construct points with placement and feel rather than heavy topspin.",
    not_ideal_for: "Beginners and intermediate players. Heavy topspin baseliners who rely on an open string pattern for spin production.",
    famous_users: "Aryna Sabalenka",
    similar_alternatives: ["Head Prestige Pro", "Yonex Percept 97D", "Tecnifibre TF40 18x20 305g"],
    recommended_string: {
      name: "Luxilon ALU Power",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "The industry benchmark co-poly trusted by more tour players than any other string. Delivers exceptional control, durability and a crisp, precise feel that pairs naturally with the Blade 98's soft flex and dense 18x20 pattern. Firm enough to add precision without overwhelming the frame's comfortable character.",
    },
  },
  {
    name: "Wilson Pro Staff 97 Classic",
    brand: "Wilson",
    category: "Control",
    head_size_sq_in: 97,
    weight_g: 315,
    balance_mm: 310,
    stiffness_ra: 66,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["aggressive baseliner", "all-court player", "serve & volley"],
    best_for_priority: ["control", "precision", "feel"],
    best_for_level: ["upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. 40 years of Pro Staff heritage in an iconic vintage black cosmetic.",
    first_racket_suitable: false,
    health_warning: "Stiff frame (66 RA) — not recommended for players with arm, elbow or wrist sensitivities.",
    strengths: "Classic point-and-shoot control frame with a direct, connected feel that tells you exactly where every ball went. Despite the thin 21.5mm beam and smaller 97 in² head, the 66 RA stiffness and 315g weight deliver surprisingly good power levels — the ball comes off the stringbed with more pace and penetration than the specs might suggest. Excellent at net and on slice. One of the most intuitive precision instruments on the market for players who already know how to hit.",
    weaknesses: "The stiffer 66 RA flex is less arm-friendly than the Blade or Prestige lines — players with arm sensitivities should be cautious. Unforgiving of late or mistimed swings; demands technically consistent ball striking.",
    ideal_profile: "An upper-intermediate to advanced all-court player or aggressive baseliner with a technically sound game who wants classic, direct control and a point-and-shoot feel. Also well-suited to serve-and-volley players who value precision at net.",
    not_ideal_for: "Beginners and intermediate players. Players with arm injuries or sensitivities. Those who prefer a softer, more arm-friendly flex.",
    famous_users: "Grigor Dimitrov, Jiri Lehecka, Roberto Bautista Agut",
    similar_alternatives: ["Head Prestige MP", "Head Prestige Tour", "Yonex Vcore Pro 97"],
    recommended_string: {
      name: "Luxilon ALU Power",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "The industry benchmark co-poly trusted by more tour players than any other string. Its crisp, precise feel pairs naturally with the Pro Staff's stiff flex and excellent plow-through. String at the lower end of the range (20kg) to compensate for the 66 RA stiffness and preserve arm comfort.",
    },
  },
  {
    name: "Wilson Ultra 100 v5",
    brand: "Wilson",
    category: "Power & Comfort",
    head_size_sq_in: 100,
    weight_g: 300,
    balance_mm: 320,
    stiffness_ra: 67,
    string_pattern: "16x19",
    price_range_eur: "150-200",
    best_for_style: ["aggressive baseliner", "all-court player"],
    best_for_priority: ["power", "spin", "comfort"],
    best_for_level: ["beginner", "intermediate", "upper-intermediate", "advanced"],
    age_sweet_spot: "18-55+",
    gender_notes: "Unisex. Endorsed by Maria Sakkari, Qinwen Zheng and Victoria Azarenka. Built for players who want fast, free power and easy access to spin.",
    first_racket_suitable: true,
    health_warning: "Relatively stiff frame (67 RA) — players with arm or elbow sensitivities should be cautious.",
    strengths: "Light at 300g and easy to swing fast, giving immediate access to pace without requiring a big, physical swing. The 100 in² head and 16x19 pattern produce good spin and a large, forgiving sweet spot. The wider dual-taper beam (up to 26.5mm) generates free power naturally — the ball comes off lively even on moderate swings. Crush Zone grommets improve ball pocketing and comfort at impact. A genuine all-levels frame that grows with the player.",
    weaknesses: "The 67 RA stiffness makes it one of the firmer frames in this weight class — less comfortable on the arm than softer alternatives like the Blade or Boom. Less precise and less connected-feeling than control-oriented frames.",
    ideal_profile: "A beginner to advanced player who wants easy, effortless power and spin from a light, fast-swinging frame. Particularly well-suited to aggressive baseliners and developing players who want pace without effort.",
    not_ideal_for: "Players who prioritise feel and control over power. Players with arm sensitivities who need a softer flex.",
    famous_users: "Maria Sakkari, Qinwen Zheng, Victoria Azarenka",
    similar_alternatives: ["Head Boom MP", "Babolat Pure Drive", "Head Speed MP"],
    recommended_string: {
      name: "Luxilon ALU Power",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "The industry benchmark co-poly delivers excellent control and durability that pairs well with the Ultra's power character. String at the lower end (20kg) to offset the 67 RA stiffness and keep the hitting experience comfortable.",
    },
  },
  {
    name: "Yonex EZONE 100",
    brand: "Yonex",
    category: "Power & Comfort",
    head_size_sq_in: 100,
    weight_g: 300,
    balance_mm: 320,
    stiffness_ra: 68,
    string_pattern: "16x19",
    price_range_eur: "220-260",
    best_for_style: ["aggressive baseliner", "all-court"],
    best_for_priority: ["power", "comfort"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "18-45. Comfortable enough for older players, powerful enough for younger ones.",
    gender_notes: "Unisex. Very popular on WTA tour.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness but Yonex's isometric head shape distributes impact well. More arm-friendly than the Pure Aero or Pure Drive despite similar stiffness numbers.",
    strengths: "The best blend of power and comfort in a 300g frame. Isometric (square-ish) head shape gives the largest sweet spot in its class. Comfortable on off-center hits where other rackets jar your arm. Excellent power with good feel.",
    weaknesses: "Not as spin-focused as the Pure Aero. Not as precise as 98 sq in control frames. Jack of all trades, master of none.",
    ideal_profile: "An intermediate-to-advanced player who wants power AND comfort. Especially good for players upgrading from beginner rackets who want a forgiving, powerful frame. Also great for players switching from stiff frames due to arm concerns.",
    not_ideal_for: "Pure spin seekers (Pure Aero is better), maximum control seekers (too powerful).",
    famous_users: "Naomi Osaka, Nick Kyrgios",
    similar_alternatives: ["Babolat Pure Aero", "Head Extreme MP"],
    recommended_string: {
      name: "Yonex Poly Tour Pro",
      type: "Polyester",
      tension_range_kg: "20-23",
      why: "Tuned for Yonex isometric frames, delivers spin and comfort without overwhelming the forgiving character of the EZONE.",
    },
  },
  {
    name: "Yonex VCORE 98",
    brand: "Yonex",
    category: "Spin & Control",
    head_size_sq_in: 98,
    weight_g: 305,
    balance_mm: 320,
    stiffness_ra: 65,
    string_pattern: "16x19",
    price_range_eur: "220-260",
    best_for_style: ["aggressive baseliner"],
    best_for_priority: ["spin", "control"],
    best_for_level: ["advanced"],
    age_sweet_spot: "18-35. Demanding but rewards good technique with massive spin.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. Comfortable for a performance frame. Better than the Pure Aero for arm health.",
    strengths: "Exceptional spin generation for a 98 sq in control frame. The best of both worlds — control-frame precision with spin-frame topspin. Good weight distribution for fast swings. Comfortable feel.",
    weaknesses: "Smaller sweet spot than 100 sq in frames. Less raw power than bigger frames. Demands clean technique.",
    ideal_profile: "An advanced aggressive baseliner who wants maximum spin from a control-oriented frame. For players who outgrew the EZONE 100 and want more precision.",
    not_ideal_for: "Beginners, intermediates, comfort seekers, serve-and-volley.",
    famous_users: "Casper Ruud",
    similar_alternatives: ["Babolat Pure Aero 98", "Head Extreme MP"],
    recommended_string: {
      name: "Luxilon ALU Power",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "Firm, precise co-poly that complements the VCORE 98's spin focus while adding the control a 98 sq in frame demands.",
    },
  },
  {
    name: "Tecnifibre Tempo 298",
    brand: "Tecnifibre",
    category: "All-Court Control & Feel",
    head_size_sq_in: 98,
    weight_g: 298,
    balance_mm: 320,
    stiffness_ra: 63,
    string_pattern: "16x19",
    price_range_eur: "190-240",
    best_for_style: ["all-court"],
    best_for_priority: ["control", "comfort"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "20-45.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Low stiffness (63 RA). Arm-friendly. Good for players with mild arm concerns.",
    strengths: "Excellent comfort and feel. Great touch at the net. Underrated brand that often outperforms more expensive options. Good value for money. Crisp, connected feel on every shot.",
    weaknesses: "Less brand recognition means fewer people to ask for opinions. Not as widely available for demo/testing. Less resale value.",
    ideal_profile: "An intermediate-to-advanced all-court player who values feel and comfort. The hidden gem for players willing to look beyond the big 4 brands. Often the best value in its class.",
    not_ideal_for: "Brand-conscious players, beginners, pure power seekers.",
    famous_users: "Daniil Medvedev",
    similar_alternatives: ["Wilson Blade 98", "Head Speed MP"],
    recommended_string: {
      name: "Tecnifibre X-One Biphase",
      type: "Multifilament",
      tension_range_kg: "20-23",
      why: "Medvedev's choice for his Tecnifibre frame. Maximises feel and comfort, perfectly complementing the Tempo's all-court character.",
    },
  },
  {
    name: "Dunlop CX 200",
    brand: "Dunlop",
    category: "Control & Precision",
    head_size_sq_in: 98,
    weight_g: 305,
    balance_mm: 320,
    stiffness_ra: 65,
    string_pattern: "16x19",
    price_range_eur: "190-240",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["control"],
    best_for_level: ["advanced"],
    age_sweet_spot: "20-40.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. Reasonable for arm health.",
    strengths: "Excellent control frame with good feel. Sonic Core technology improves vibration dampening. A serious player's racket at a competitive price point. Great value.",
    weaknesses: "Less power than competitors. Dunlop has less brand cachet than Head or Wilson. Smaller selection of colour options.",
    ideal_profile: "An advanced all-court player or aggressive baseliner who wants a quality control frame without paying Wilson or Head premium prices.",
    not_ideal_for: "Beginners, power seekers, brand-conscious players.",
    famous_users: "Kevin Anderson (retired)",
    similar_alternatives: ["Wilson Blade 98", "Tecnifibre Tempo 298"],
    recommended_string: {
      name: "Luxilon ALU Power",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "Precision-oriented poly for a precision-oriented frame. Keeps shots penetrating and exactly where you aim.",
    },
  },
  {
    name: "Dunlop SX 300",
    brand: "Dunlop",
    category: "Spin & Power",
    head_size_sq_in: 100,
    weight_g: 300,
    balance_mm: 320,
    stiffness_ra: 67,
    string_pattern: "16x19",
    price_range_eur: "180-230",
    best_for_style: ["aggressive baseliner"],
    best_for_priority: ["spin", "power"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "18-40.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. Average arm-friendliness.",
    strengths: "Dunlop's spin-focused frame. Good topspin generation with a comfortable feel. Spin Boost grommets amplify string movement. Competitive alternative to the Pure Aero at a lower price.",
    weaknesses: "Less brand recognition. Not quite the spin level of the Pure Aero. Can feel less precise than the CX line.",
    ideal_profile: "An intermediate-to-advanced aggressive baseliner wanting a spin-focused racket at a better price than Babolat or Head alternatives.",
    not_ideal_for: "Beginners, control purists, brand-conscious players.",
    famous_users: "",
    similar_alternatives: ["Babolat Pure Aero", "Head Extreme MP"],
    recommended_string: {
      name: "Solinco Hyper-G",
      type: "Polyester",
      tension_range_kg: "20-23",
      why: "Spin-amplifying poly pairs perfectly with the SX 300's spin-focused design and Spin Boost grommets.",
    },
  },
  {
    name: "Diadem Elevate 98",
    brand: "Diadem",
    category: "Control & Power",
    head_size_sq_in: 98,
    weight_g: 305,
    balance_mm: 320,
    stiffness_ra: 64,
    string_pattern: "16x19",
    price_range_eur: "180-220",
    best_for_style: ["all-court", "aggressive baseliner"],
    best_for_priority: ["control", "power"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "20-40.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Low stiffness. Arm-friendly.",
    strengths: "The exciting newcomer. Clean, modern design with excellent feel. Made with high-quality Japanese carbon. Outstanding value — premium performance at a mid-range price. Diadem is building a cult following among knowledgeable players.",
    weaknesses: "Very new brand — limited track record. Harder to find in shops for demo. Smaller community of users to consult.",
    ideal_profile: "An intermediate-to-advanced player who doesn't care about brand name and wants a high-quality, well-priced racket. For players who enjoy discovering overlooked gems.",
    not_ideal_for: "Brand-conscious players, beginners, players who want to try before buying (limited demo availability).",
    famous_users: "Growing presence among college and lower-tour professionals",
    similar_alternatives: ["Wilson Blade 98", "Head Speed MP"],
    recommended_string: {
      name: "Luxilon ALU Power",
      type: "Co-Polyester",
      tension_range_kg: "20-22",
      why: "Control-first poly for a control-first frame. Keeps shots penetrating and precise.",
    },
  },
  {
    name: "Diadem Nova 100",
    brand: "Diadem",
    category: "Power & Spin",
    head_size_sq_in: 100,
    weight_g: 300,
    balance_mm: 320,
    stiffness_ra: 67,
    string_pattern: "16x19",
    price_range_eur: "170-210",
    best_for_style: ["aggressive baseliner", "all-court"],
    best_for_priority: ["power", "spin"],
    best_for_level: ["intermediate", "advanced"],
    age_sweet_spot: "18-40.",
    gender_notes: "Unisex.",
    first_racket_suitable: false,
    health_warning: "Moderate stiffness. Average arm-friendliness.",
    strengths: "Power-oriented frame with good spin from a challenger brand. Excellent price-to-performance ratio. Japanese carbon construction. Modern aesthetics.",
    weaknesses: "New brand with limited recognition. Harder to find for testing. Unproven long-term durability track record.",
    ideal_profile: "An intermediate-to-advanced aggressive baseliner looking for a powerful, spin-friendly frame at a price well below the big brands.",
    not_ideal_for: "Brand loyalists, beginners, players who need to demo extensively.",
    famous_users: "Emerging presence in college tennis",
    similar_alternatives: ["Babolat Pure Aero", "Dunlop SX 300"],
    recommended_string: {
      name: "Solinco Hyper-G",
      type: "Polyester",
      tension_range_kg: "20-23",
      why: "Spin-first poly for a power and spin frame. Maximises topspin while maintaining durability.",
    },
  },
];

export function getRacketDatabaseText(): string {
  return RACKET_DATABASE.map((r) => [
    `### ${r.name} (${r.brand})`,
    `Category: ${r.category}`,
    `Head: ${r.head_size_sq_in} sq in | Weight: ${r.weight_g}g | Balance: ${r.balance_mm}mm | Stiffness: ${r.stiffness_ra} RA | Pattern: ${r.string_pattern}`,
    `Price: €${r.price_range_eur}`,
    `Best for levels: ${r.best_for_level.join(", ")}`,
    `Best for styles: ${r.best_for_style.join(", ")}`,
    `Best for priorities: ${r.best_for_priority.join(", ")}`,
    `Age notes: ${r.age_sweet_spot}`,
    `Health/arm notes: ${r.health_warning}`,
    `Strengths: ${r.strengths}`,
    `Weaknesses: ${r.weaknesses}`,
    `Ideal profile: ${r.ideal_profile}`,
    `Not ideal for: ${r.not_ideal_for}`,
    `Similar alternatives: ${r.similar_alternatives.join(", ")}`,
    `Recommended string: ${r.recommended_string.name} | Type: ${r.recommended_string.type} | Tension: ${r.recommended_string.tension_range_kg} kg`,
    ...(r.famous_users ? [`Used by: ${r.famous_users}`] : []),
    "",
  ].join("\n")).join("\n");
}
